Vhdl parse cleanups
ghdl/ghdl pull request #1707
Opened 2021-04-03 11:30 UTC by Blebowski

**Description** Please explain the changes you made here.
Improve error/warning logging. Following is done (mostly in VHDL parser and Errorout):
 - If available, print also source code line + location marker where error/warning occured (mimic other compilers)
 - Missing parenthesis are reported only once. If multiple are missing, total missing count is reported. (Resolves FIXME)
 - Improve Invalid shared/non-shared variable error report in cases if variable is declared where it should not be. (Resolves FIXME)
 - give hint if ':=' is used for alias instead of 'is' (resolves FIXME)
 - add resynchronization to end of external name (resolves FIXME)
 - remove FIXME for parsing of file_open_information. AFAIK combination of file_open_kind and file_mode are handled
   correctly, and no FIX is needed. If no file_open_information is present READ_MODE is assumed.

:rotating_light: Before submitting your PR, please read [contribute](http://ghdl.readthedocs.io/en/latest/contribute.html#fork-modify-and-pull-request) in the [Docs](http://ghdl.readthedocs.io/en/latest/index.html), and review the following checklist:

- [x] No issue closed. Feature added was not in any open issue. FIXMEs were searched through the code.

**When contributing to the GHDL codebase...**

- [x] DO make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] DO make sure you are making a pull request against the **master branch** (left side). Also you should start *your branch* off *our master*.
- [x] DO make sure that GHDL can be successfully built. See [Building GHDL](https://github.com/ghdl/ghdl#building-ghdl).
- [ ] CONSIDER adding a unit test if your PR resolves an issue. **AFAIK , No issue resolved by this PR**.
- [x] CONSIDER modifying the docs, at least in the TODO, if your contribution is relevant to any of the content.
- [x] AVOID breaking the continuous integration build.
- [x] AVOID breaking the testsuite. **All tests which relied on exact error output format has been adjusted.**

**When contributing to the docs...**

Not contributing to the docs.

**Further comments**

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did, what alternatives you considered, etc.

For FIXMEs: It is a good way how to get to know the codebase, therefore I started with FIXMEs.
For detailed logging: Inspired by other compilers (LLVM, Slang), IMHO it makes easier to debug. First thing a user
  will do after error, is anyway search line and column in source code at which the error occured.
TBD: At the moment this behavior is default (each reported message, note, warning, error). It is possible
         we could disable it by default, and enable with -v flag? Or is it reasonable to keep it default??

2021-04-03 11:47 UTC, tgingold commented
Please create one pull-request per feature.  This is much easier to review and to commit.  And it will also increase your number of commits!

General comment: remove useless parenthesis within `if`/`then`, add a space before `(` and a newline before `is` when there are declarations.

I think you have duplicated the `-fcaret-diagnostics` feature.  Maybe it should be the default ?

I will review soon.

2021-04-03 11:49 UTC, tgingold commented on src/vhdl/vhdl-parse.adb
> +      end if;
That's ok but you have to remove the parenthesis in between if/then.

2021-04-03 12:45 UTC, Blebowski commented
Hi,
thanks.
Carret diagnostics: Oh, I should have noticed that... Sorry. I will discard this commit. Having "-fcaret-diagnostics" as default sounds good.

FIXMEs: I will create one pull request per fix.
Coding style: I will fix that.

2021-04-03 17:33 UTC, umarcor commented
> Having "-fcaret-diagnostics" as default sounds good.

Agree.

2021-04-03 17:40 UTC, umarcor commented
@blebowski, you can use `[ ]` and `[x]` for keeping track of which features were merged already. For instance:

* [ ] <strike>If available, print also source code line + location marker where error/warning occured (mimic other compilers)</strike> Have `fcaret-diagnostics` as default.
* [ ] #1712: Missing parenthesis are reported only once. If multiple are missing, total missing count is reported. (Resolves FIXME)
* [x] #1711: Improve Invalid shared/non-shared variable error report in cases if variable is declared where it should not be. (Resolves FIXME)
* [x] #1710: give hint if ':=' is used for alias instead of 'is' (resolves FIXME)
* [ ] #1709: add resynchronization to end of external name (resolves FIXME)
* [ ] remove FIXME for parsing of file_open_information. AFAIK combination of file_open_kind and file_mode are handled  correctly, and no FIX is needed. If no file_open_information is present READ_MODE is assumed.

2021-04-03 18:31 UTC, tgingold requested changes

2021-04-05 16:28 UTC, Blebowski commented on src/vhdl/vhdl-parse.adb
> +      Prefix : String (1 .. 11) := (others => Character'Val(0));
Hi, thanks for fixing the coding style and merging. With `c585924` empty characters (next note) are not printed.

2021-04-06 05:52 UTC, tgingold commented on src/vhdl/vhdl-parse.adb
> +      Prefix : String (1 .. 11) := (others => Character'Val(0));
I am not sure to understand.

2021-04-06 05:54 UTC, tgingold commented
Most of this PR has been merged with the other PR you submitted.
Maybe it should be closed and the remaining changes submitted as a new PR.

2021-04-08 10:55 UTC, Blebowski commented
> Most of this PR has been merged with the other PR you submitted.
> Maybe it should be closed and the remaining changes submitted as a new PR.

I agree, it can be closed. The only remaining thing is: `c585924` . I can cherry-pick it and provide separate PR.

2021-04-08 18:25 UTC, closed without merging